// THIS FILE IS GENERATED BY TOOL, PLEASE DON'T EDIT

#include "XMLData.h"
#include "tinyxml.h"

#define XML_SET_ATTR_INT(_node, _from, _to) {0} \
	if (_node && _from) {0} const char* value = _node->Attribute(_from); \
		if (value) sscanf(value, "%d", &_to); else _to = 0; \
	{1} \
{1}

#define XML_SET_ATTR_FLOAT(_node, _from, _to) {0} \
	if (_node && _from) {0} const char* value = _node->Attribute(_from); \
		if (value) sscanf(value, "%f", &_to); else _to = 0.f; \
	{1} \
{1}

#define XML_SET_ATTR_TEXT(_node, _from, _to) {0} \
	if (_node && _from) {0} const char* value = _node->Attribute(_from); \
		if (value) _to = value; else _to = ""; \
	{1} \
{1}

{2}
