// THIS FILE IS GENERATED BY TOOL, PLEASE DON'T EDIT

#include "XMLManager.h"
#include "cocos2d.h"

USING_NS_CC;

#define LOAD_XML_FILE(FileName) \
	TiXmlDocument document = loadFromFile(FileName)

#define LOAD_TABLE_DATA(TableName) \
	XML_VAR(TableName).load(document.FirstChildElement(#TableName))

XMLManager::XMLManager()
: m_bInited(false)
{0}
{1}

XMLManager::~XMLManager()
{0}
{1}

XMLManager& XMLManager::sharedInstance()
{0}
	static XMLManager s_instance;
	return s_instance;
{1}

void XMLManager::loadData()
{0}
	if (!m_bInited) {0}
		m_bInited = true;
{2}
	{1}
{1}

TiXmlDocument XMLManager::loadFromFile(const char* filename)
{0}
	unsigned long size = 0;
	unsigned char* data = NULL;
	data = CCFileUtils::sharedFileUtils()->getFileData(filename, "rb", &size);

	TiXmlDocument document;
	document.Parse((const char*)data);
	return document;
{1}
